#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

generate_git_signing_key () {
	local key_type="${1:-ed25519}"
	local key_path="$HOME/.ssh/${2:-git}"
	
	ssh-keygen -t "$key_type" -f "$key_path" -N "" -q

	chmod 600 "$key_path"
	chmod 644 "$key_path.pub"

	git config --global user.signingkey $key_path
}

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
generate_git_signing_key

# Keyd
sudo ln -sf $DOTFILES/keyd/default.conf /etc/keyd/default.conf 

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

cp $DOTFILES/zsh/zshrc $HOME/.zshrc
