#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Ghostty
rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty 

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

# yt-dlp
rm -rf $HOME/.config/youtube-dl
ln -s $DOTFILES/yt-dlp $HOME/.config/youtube-dl

# Tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi


# hammerspoon
rm -rf $HOME/.hammerspoon
ln -s $DOTFILES/hammerspoon $HOME/.hammerspoon

# Zsh
if [ ! -f "$HOME/.zshrc" ]; then
    cp "$DOTFILES/zsh/zshrc" "$HOME/.zshrc"
		ln -sf $DOTFILES/zsh/command-not-found $HOME/.command-not-found
		ln -sf $DOTFILES/zsh/docebo $HOME/.docebo
		ln -sf $DOTFILES/zsh/yt-dlp $HOME/.yt-dlp
fi

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Starship
rm -rf $HOME/.config/starship.toml
rm -rf $HOME/.config/jetbrains.toml
ln -s $DOTFILES/starship/starship.toml $HOME/.config/starship.toml
ln -s $DOTFILES/starship/jetbrains.toml $HOME/.config/jetbrains.toml

if ! command -v starship >/dev/null 2>&1; then
    mkdir -p "$HOME/.local/bin"
    BIN_DIR="$HOME/.local/bin" FORCE=1 sh -c "$(curl -fsSL https://starship.rs/install.sh)"
fi
