"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$directory$git_branch$git_status """
right_format = """$character$time"""

palette = 'everforest'

[directory]
style = "bg:blue fg:crust"
format = "[](bg:blue fg:blue)[$path ]($style)[](blue)"
truncation_length = 8
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:orange italic"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:orange italic"
format = "[($all_status$ahead_behind )]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:gray"
format = "[[](fg:gray)[ $time](fg:crust bg:gray)]($style)[](fg:gray bg:gray)"

[character]
disabled = false
format = "[$symbol ](bg:none)"
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[palettes.everforest]
red = "#f85552"
orange = "#f57d26"
green = "#8da101"
blue = "#3a94c5"
purple = "#df69ba"
gray = "#829181"
crust = "#ecf5ed"
