export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""
ZSH_DISABLE_COMPFIX="true"
HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

export ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump"

plugins=(
  colorize
  cp
  docker
  docker-compose
  git
  zsh-autosuggestions
)

zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
alias vim="nvim"

export LANG=it_IT.UTF-8

export UID="$(id -u)"
export GID="$(id -g)"

export DOCKER_CLI_HINTS='false'

export PATH=$HOME/bin:$HOME/.local/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH

if [ "$TERMINAL_EMULATOR" = "JetBrains-JediTerm" ]; then
    export STARSHIP_CONFIG=~$HOME/.config/jetbrains.toml
fi

eval "$(starship init zsh)"

nah () {
    git reset --hard
    git clean -df

    if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
        git rebase --abort
    fi
}

function tab_name () { echo -ne "\033]0;${PWD/#$HOME/~}\007" }
precmd_functions+=(tab_name)

source $HOME/.yt-dlp

### Funny stuff ###
[ ! -f $HOME/.command-not-found ] || source $HOME/.command-not-found
### Funny stuff ###

### Docebo ###
source $HOME/.docebo
[[ -f "$HOME/Docebo/Learn/local/scripts/.completion/_wand_completion.zsh" ]] && \. "$HOME/Docebo/Learn/local/scripts/.completion/_wand_completion.zsh"
### Docebo ###
