export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""
ZSH_DISABLE_COMPFIX="true"

HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  colorize
  cp
  docker
  docker-compose
  git
  zsh-autosuggestions
)

zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
export LANG=it_IT.UTF-8

export UID="$(id -u)"
export GID="$(id -g)"

export DOCKER_CLI_HINTS='false'

export PATH=$HOME/bin:$HOME/.local/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH

eval "$(starship init zsh)"

nah () {
    git reset --hard
    git clean -df

    if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
        git rebase --abort
    fi
}

function tab_name () { echo -ne "\033]0;${PWD/#$HOME/~}\007" }
precmd_functions+=(tab_name)

source $HOME/.yt-dlp

### Funny stuff ###
[ ! -f $HOME/.command-not-found ] || source $HOME/.command-not-found
eval $(thefuck --alias)
### Funny stuff ###

### Node Version Manager ###
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
### Node Version Manager ###

### Docebo ###
source $HOME/.docebo
[[ -f "$HOME/Docebo/Learn/local/scripts/.completion/_wand_completion.zsh" ]] && \. "$HOME/Docebo/Learn/local/scripts/.completion/_wand_completion.zsh"
### Docebo ###

### Docker ###
export PATH=$HOME/.docker/bin:$PATH
fpath=("$HOME/.docker/completions" $fpath)
autoload -Uz compinit
compinit
### Docker ###

### Herd ###
export PATH="$HOME/Library/Application Support/Herd/bin/":$PATH
export HERD_PHP_83_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/83/"
export HERD_PHP_84_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/84/"
### Herd ###

# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/simone.peniti/Library/Application Support/Herd/config/php/84/"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/simone.peniti/Library/Application Support/Herd/config/php/83/"
