export ZSH="$HOME/.oh-my-zsh"

ZSH_THME="robbyrussell"
ZSH_DISABLE_COMPFIX="true"

HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

export ZSH_COMPDUMP="$HOME/.cache/zsh/zcompdump"

plugins=(
  colorize
  cp
  docker
  docker-compose
  git
)

zstyle ':omz:plugins:nvm' lazy yes
zstyle ':omz:plugins:nvm' lazy-cmd eslint prettier typescript

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
export LANG=it_IT.UTF-8

export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH

nah () {
    git reset --hard
    git clean -df

    if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
        git rebase --abort
    fi
}

function tab_name () { echo -ne "\033]0;${PWD/#$HOME/~}\007" }
precmd_functions+=(tab_name)
